// <auto-generated />
using System;
using Legacy.Maliev.ProcurementService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.ProcurementService.Data.Migrations.PurchaseOrder
{
    [DbContext(typeof(PurchaseOrderDbContext))]
    [Migration("20261011073000_AddDurablePurchaseOrderChildReceipts")]
    partial class AddDurablePurchaseOrderChildReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Data.CreateReceiptRecord", b =>
                {
                    b.Property<byte[]>("IssuerDigest")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SubjectDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("Operation")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("KeyDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("CanonicalVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("ResponseVersion")
                        .HasColumnType("smallint");

                    b.HasKey("IssuerDigest", "SubjectDigest", "Operation", "KeyDigest")
                        .HasName("PK_PurchaseOrderCreateReceipt");

                    b.ToTable("PurchaseOrderCreateReceipt", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderCreateReceipt_Complete", "\"EntityId\" > 0 AND octet_length(\"ResponseBody\") > 0");

                            t.HasCheckConstraint("CK_PurchaseOrderCreateReceipt_Digests", "octet_length(\"IssuerDigest\") = 32 AND octet_length(\"SubjectDigest\") = 32 AND octet_length(\"KeyDigest\") = 32 AND octet_length(\"PayloadDigest\") = 32 AND octet_length(\"ResponseDigest\") = 32");

                            t.HasCheckConstraint("CK_PurchaseOrderCreateReceipt_Operation", "\"Operation\" = 2");

                            t.HasCheckConstraint("CK_PurchaseOrderCreateReceipt_Versions", "\"CanonicalVersion\" = 1 AND \"ResponseVersion\" = 1");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Data.OrderItemChildReceiptRecord", b =>
                {
                    b.Property<byte[]>("IssuerDigest")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SubjectDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("Operation")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("KeyDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("CanonicalVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("ResponseVersion")
                        .HasColumnType("smallint");

                    b.HasKey("IssuerDigest", "SubjectDigest", "Operation", "KeyDigest")
                        .HasName("PK_OrderItemCreateReceipt");

                    b.ToTable("OrderItemCreateReceipt", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItemCreateReceipt_Complete", "\"EntityId\" > 0 AND octet_length(\"ResponseBody\") > 0");

                            t.HasCheckConstraint("CK_OrderItemCreateReceipt_Digests", "octet_length(\"IssuerDigest\") = 32 AND octet_length(\"SubjectDigest\") = 32 AND octet_length(\"KeyDigest\") = 32 AND octet_length(\"PayloadDigest\") = 32 AND octet_length(\"ResponseDigest\") = 32");

                            t.HasCheckConstraint("CK_OrderItemCreateReceipt_Operation", "\"Operation\" = 3");

                            t.HasCheckConstraint("CK_OrderItemCreateReceipt_Versions", "\"CanonicalVersion\" = 1 AND \"ResponseVersion\" = 1");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Data.FileChildReceiptRecord", b =>
                {
                    b.Property<byte[]>("IssuerDigest")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SubjectDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("Operation")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("KeyDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("CanonicalVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("ResponseVersion")
                        .HasColumnType("smallint");

                    b.HasKey("IssuerDigest", "SubjectDigest", "Operation", "KeyDigest")
                        .HasName("PK_PurchaseOrderFileCreateReceipt");

                    b.ToTable("PurchaseOrderFileCreateReceipt", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderFileCreateReceipt_Complete", "\"EntityId\" > 0 AND octet_length(\"ResponseBody\") > 0");

                            t.HasCheckConstraint("CK_PurchaseOrderFileCreateReceipt_Digests", "octet_length(\"IssuerDigest\") = 32 AND octet_length(\"SubjectDigest\") = 32 AND octet_length(\"KeyDigest\") = 32 AND octet_length(\"PayloadDigest\") = 32 AND octet_length(\"ResponseDigest\") = 32");

                            t.HasCheckConstraint("CK_PurchaseOrderFileCreateReceipt_Operation", "\"Operation\" = 4");

                            t.HasCheckConstraint("CK_PurchaseOrderFileCreateReceipt_Versions", "\"CanonicalVersion\" = 1 AND \"ResponseVersion\" = 1");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("PurchaseOrderID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("OrderItem", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_PartNumber_UTF16", "char_length(\"PartNumber\") + char_length(regexp_replace(\"PartNumber\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 100");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("integer")
                        .HasColumnName("BillingAddressID");

                    b.Property<string>("BillingContactPerson")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BillingFax")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BillingMobile")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BillingTelephone")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Fob")
                        .HasColumnType("text")
                        .HasColumnName("FOB");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("integer")
                        .HasColumnName("ShippingAddressID");

                    b.Property<string>("ShippingContactPerson")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShippingFax")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShippingMobile")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShippingTelephone")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SupplierContactPerson")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("SupplierID");

                    b.Property<string>("Terms")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("PurchaseOrder", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrder_BillingContactPerson_UTF16", "char_length(\"BillingContactPerson\") + char_length(regexp_replace(\"BillingContactPerson\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_BillingFax_UTF16", "char_length(\"BillingFax\") + char_length(regexp_replace(\"BillingFax\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_BillingMobile_UTF16", "char_length(\"BillingMobile\") + char_length(regexp_replace(\"BillingMobile\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_BillingTelephone_UTF16", "char_length(\"BillingTelephone\") + char_length(regexp_replace(\"BillingTelephone\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_ShippingContactPerson_UTF16", "char_length(\"ShippingContactPerson\") + char_length(regexp_replace(\"ShippingContactPerson\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_ShippingFax_UTF16", "char_length(\"ShippingFax\") + char_length(regexp_replace(\"ShippingFax\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_ShippingMethod_UTF16", "char_length(\"ShippingMethod\") + char_length(regexp_replace(\"ShippingMethod\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_ShippingMobile_UTF16", "char_length(\"ShippingMobile\") + char_length(regexp_replace(\"ShippingMobile\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_ShippingTelephone_UTF16", "char_length(\"ShippingTelephone\") + char_length(regexp_replace(\"ShippingTelephone\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_SupplierContactPerson_UTF16", "char_length(\"SupplierContactPerson\") + char_length(regexp_replace(\"SupplierContactPerson\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_PurchaseOrder_Terms_UTF16", "char_length(\"Terms\") + char_length(regexp_replace(\"Terms\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Building")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("CountryID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("State")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_Address_AddressLine1_UTF16", "char_length(\"AddressLine1\") + char_length(regexp_replace(\"AddressLine1\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_AddressLine2_UTF16", "char_length(\"AddressLine2\") + char_length(regexp_replace(\"AddressLine2\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_Building_UTF16", "char_length(\"Building\") + char_length(regexp_replace(\"Building\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_City_UTF16", "char_length(\"City\") + char_length(regexp_replace(\"City\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_PostalCode_UTF16", "char_length(\"PostalCode\") + char_length(regexp_replace(\"PostalCode\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_State_UTF16", "char_length(\"State\") + char_length(regexp_replace(\"State\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("PurchaseOrderID");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderFile", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderFile_Bucket_UTF16", "char_length(\"Bucket\") + char_length(regexp_replace(\"Bucket\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 50");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.OrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.ProcurementService.Domain.PurchaseOrder", "PurchaseOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OrderItem_PurchaseOrder");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderAddress", "BillingAddress")
                        .WithMany("BillingPurchaseOrders")
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PurchaseOrder_Address1");

                    b.HasOne("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderAddress", "ShippingAddress")
                        .WithMany("ShippingPurchaseOrders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PurchaseOrder_Address");

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderFile", b =>
                {
                    b.HasOne("Legacy.Maliev.ProcurementService.Domain.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Files")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrderFile_PurchaseOrder");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.PurchaseOrderAddress", b =>
                {
                    b.Navigation("BillingPurchaseOrders");

                    b.Navigation("ShippingPurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
