// <auto-generated />
using System;
using Legacy.Maliev.ProcurementService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.ProcurementService.Data.Migrations.Supplier
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20261006210000_PreserveSupplierSourceStringBoundaries")]
    partial class PreserveSupplierSourceStringBoundaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Data.CreateReceiptRecord", b =>
                {
                    b.Property<byte[]>("IssuerDigest")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SubjectDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("Operation")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("KeyDigest")
                        .HasColumnType("bytea");

                    b.Property<short>("CanonicalVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ResponseDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("ResponseVersion")
                        .HasColumnType("smallint");

                    b.HasKey("IssuerDigest", "SubjectDigest", "Operation", "KeyDigest")
                        .HasName("PK_SupplierCreateReceipt");

                    b.ToTable("SupplierCreateReceipt", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupplierCreateReceipt_Complete", "\"EntityId\" > 0 AND octet_length(\"ResponseBody\") > 0");

                            t.HasCheckConstraint("CK_SupplierCreateReceipt_Digests", "octet_length(\"IssuerDigest\") = 32 AND octet_length(\"SubjectDigest\") = 32 AND octet_length(\"KeyDigest\") = 32 AND octet_length(\"PayloadDigest\") = 32 AND octet_length(\"ResponseDigest\") = 32");

                            t.HasCheckConstraint("CK_SupplierCreateReceipt_Operation", "\"Operation\" = 1");

                            t.HasCheckConstraint("CK_SupplierCreateReceipt_Versions", "\"CanonicalVersion\" = 1 AND \"ResponseVersion\" = 1");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("AddressID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Fax")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Supplier", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_Supplier_Email_UTF16", "char_length(\"Email\") + char_length(regexp_replace(\"Email\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_Fax_UTF16", "char_length(\"Fax\") + char_length(regexp_replace(\"Fax\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_Mobile_UTF16", "char_length(\"Mobile\") + char_length(regexp_replace(\"Mobile\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_Name_UTF16", "char_length(\"Name\") + char_length(regexp_replace(\"Name\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_TaxNumber_UTF16", "char_length(\"TaxNumber\") + char_length(regexp_replace(\"TaxNumber\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_Telephone_UTF16", "char_length(\"Telephone\") + char_length(regexp_replace(\"Telephone\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Supplier_Website_UTF16", "char_length(\"Website\") + char_length(regexp_replace(\"Website\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.SupplierAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Address2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Building")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("CountryID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("State")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_Address_Address1_UTF16", "char_length(\"Address1\") + char_length(regexp_replace(\"Address1\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_Address2_UTF16", "char_length(\"Address2\") + char_length(regexp_replace(\"Address2\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_Building_UTF16", "char_length(\"Building\") + char_length(regexp_replace(\"Building\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_City_UTF16", "char_length(\"City\") + char_length(regexp_replace(\"City\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_PostalCode_UTF16", "char_length(\"PostalCode\") + char_length(regexp_replace(\"PostalCode\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                            t.HasCheckConstraint("CK_Address_State_UTF16", "char_length(\"State\") + char_length(regexp_replace(\"State\", U&'[^\\+010000-\\+10FFFF]', '', 'g')) <= 256");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.Supplier", b =>
                {
                    b.HasOne("Legacy.Maliev.ProcurementService.Domain.SupplierAddress", "Address")
                        .WithMany("Suppliers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Supplier_Address");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Legacy.Maliev.ProcurementService.Domain.SupplierAddress", b =>
                {
                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
